Added getTrack, removed redundant ifs
atp-mipt/jsyntrax pull request #25
Opened 2020-12-22 16:35 UTC by mikhailyumanov

2020-12-22 17:57 UTC, inponomarev requested changes
Nice, isn't it satisfying when you make code shorter? :-)

General wish: can you think of making more fields `private final`?

NB: if you're using IDEA, you can try Analyze->Inspect Code->Whole Project, and then find Inspection Results -> Java -> Declaration Redundancy -> Declaration can have final modifier as a starting point.

Then, under 'unused declarations' you will find things that can be safely deleted :-)

2020-12-22 17:57 UTC, inponomarev commented on jsyntrax/src/main/java/org/atpfivt/jsyntrax/Configuration.java
>          this.urlMap = new HashMap<>();
`Collections.emptyMap()` ?

2020-12-24 20:48 UTC, mikhailyumanov commented on jsyntrax/src/main/java/org/atpfivt/jsyntrax/Configuration.java
>          this.urlMap = new HashMap<>();
Fixed

2020-12-25 08:28 UTC, inponomarev approved these changes

2020-12-25 08:28 UTC, merged